# This is .github/workflows/main.yml or similar

# name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser feedgen
    - name: Run aggregator script
      run: |
        python rss-aggregator/aggregator.py > rss-aggregator/feed.xml
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss-aggregator/feed.xml
        git commit -m "Update feed"
        git push
